language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: python=3.5 CONDA_PY=3.5
    - os: linux
      dist: trusty
      sudo: false
      env: python=3.6 CONDA_PY=3.6
    - os: osx
      osx_image: xcode7.3
      env: CONDA_PY=3.5
    - os: osx
      osx_image: xcode7.3
      env: CONDA_PY=3.6

before_install:
  - export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
  - echo $TRAVIS_COMMIT_MSG
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip travis\]'; export DISABLE_TRAVIS=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[enaml-pygments\]'; export BUILD_ENAML_PYGMENTS=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[argh\]'; export BUILD_ARGH=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[pyclibrary\]'; export BUILD_PYCLIBRARY=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[pathtools\]'; export BUILD_PATHTOOLS=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[watchdog\]'; export BUILD_WATCHDOG=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[pyvisa\]'; export BUILD_PYVISA=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[atom\]'; export BUILD_ATOM=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[kiwisolver\]'; export BUILD_KIWISOLVER=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[enaml\]'; export BUILD_ENAML=$?; true
  - echo "argh" $BUILD_ARGH "pathtools" $BUILD_PATHTOOLS "watchdog" $BUILD_WATCHDOG
  - echo "enaml-pygments" $BUILD_ENAML_PYGMENTS "pyclibrary" BUILD_PYCLIBRARY
  - echo "atom" $BUILD_ATOM "kiwi" $BUILD_KIWISOLVER "enaml" $BUILD_ENAML


install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then rvm get stable; fi
  - if [[ $DISABLE_TRAVIS != 0 ]]; then source continuous-integration/travis/install.sh; fi
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)
  - cd ..
  - if [[ $DISABLE_TRAVIS != 0 ]]; then conda config --add channels exopy; fi

script:
  - bash continuous-integration/travis/build-packages.sh

after_success:
  - cd conda-bld-out
  - if [[ $DISBALE_TRAVIS != 0 ]] & [[ $TRAVIS_SECURE_ENV_VARS ]]; then python ../continuous-integration/anaconda-push.py; fi
