language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: python=2.7 CONDA_PY=27
    - os: linux
      dist: trusty
      sudo: false
      env: python=3.4 CONDA_PY=34
    - os: linux
      dist: trusty
      sudo: false
      env: python=3.5 CONDA_PY=35
    - os: osx
      osx_image: xcode7.3
      env: CONDA_PY=27
    - os: osx
      osx_image: xcode7.3
      env: CONDA_PY=34
    - os: osx
      osx_image: xcode7.3
      env: CONDA_PY=35

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '[argh]'; export BUILD_ARGH=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '[pathtools]'; export BUILD_PATHTOOLS=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '[watchdog]'; export BUILD_WATCHDOG=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '[atom]'; export BUILD_ATOM=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '[kiwisolver]'; export BUILD_KIWISOLVER=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '[enaml]'; export BUILD_ENAML=$?; true

install:
  - source continuous-integration/travis/install.sh
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)
  - cd ..
  - conda config --add channels ecpy

script:
  - source continuous-integration/travis/build-packages.sh

after_success:
  - cd conda-bld-out
  # Will uncomment once the build is stable
  # - anaconda upload -t $ANACONDA_TOKEN upload --force *.tar.bz2
