environment:
  # See README for information on the token
  # anaconda_token:
  #   secure: va2cH3651uru58ThstGxm6R/Rvjw4xC13WnQFQpP0bgc8IjYrbBJWLLMvrCuSgWF

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

  anaconda_token:
    secure: yl5bzFz+YXs8yVsyapLFzoWYRE6GXHkl6Qx2DcfSmCEZE9H/RiXs3Yegl7jpk6dr

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the anaconda CLI
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install conda-build==1.20.3

  # Determine which packages to build
  # Use cd as true on bash to set the status to 0
  - SET COMMIT_MSG=%APPVEYOR_REPO_COMMIT_MESSAGE%\n%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%
  - echo %COMMIT_MSG%
  - echo.%COMMIT_MSG%|findstr /C:"\[atom\]" >nul 2>&1 && set BUILD_ATOM=0 || set BUILD_ATOM=1
  - echo.%COMMIT_MSG%|findstr /C:"\[kiwisolver\]" >nul 2>&1 && set BUILD_KIWISOLVER=0 || set BUILD_KIWISOLVER=1
  - echo.%COMMIT_MSG%|findstr /C:"\[enaml\]" >nul 2>&1 && set BUILD_ENAML=0 || set BUILD_ENAML=1
  - echo "atom" %BUILD_ATOM% "kiwi" %BUILD_KIWISOLVER% "enaml" %BUILD_ENAML%

  - mkdir conda-bld-out
  - cd conda-bld-out
  - set CONDA_BLD_PATH=%cd%
  - cd ..
  - conda config --add channels ecpy

build: false

test_script:
  - "%CMD_IN_ENV% .\\continuous-integration\\appveyor\\build-atom.bat"
  - python .\\continuous-integration\\appveyor\\rm_rf.py .\\%CONDA_BLD_PATH%\\work
  - "%CMD_IN_ENV% .\\continuous-integration\\appveyor\\build-kiwisolver.bat"
  - python .\\continuous-integration\\appveyor\\rm_rf.py .\\%CONDA_BLD_PATH%\\work
  - "%CMD_IN_ENV% .\\continuous-integration\\appveyor\\build-enaml.bat"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*\\*.tar.bz2'

on_success:
  # Upload built binaries to anaconda.org. The globbing and handling of the
  # exit-status code is tricky in cmd.exe or powershell, so we're just using
  # a python script.
  - cd %CONDA_BLD_PATH%
  - if defined ANACONDA_TOKEN (
      python ..\\continuous-integration\\anaconda-push.py
    )
