package:
  name: watchdog
  version: "0.10.3"

source:
  fn: watchdog-0.10.3.tar.gz
  url: https://pypi.python.org/packages/source/w/watchdog/watchdog-0.10.3.tar.gz
  md5: 9a5c9134e943b534b9f8b51d78338cf8

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - watchdog = watchdog:main
    #
    # Would create an entry point called watchdog that calls watchdog.main()

    - watchmedo = watchdog.watchmedo:main


requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.10
    - argh >=0.24.1
    - pathtools >=0.1.1

  run:
    - python
    - pyyaml >=3.10
    - argh >=0.24.1
    - pathtools >=0.1.1

test:
  # Python imports
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.tricks
    - watchdog.utils

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: Apache Software License
  summary: 'Filesystem events monitoring'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
