package:
  name: enaml
  version: 0.9.9

source:
  git_url: https://github.com/MatthieuDartiailh/enaml.git
  git_tag: python3-parsing
  patches:
    - rm-byteplay2.patch [py3k]
    - rm-byteplay3.patch [py2k]

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - enaml-run = enaml.runner:main
  osx_is_app: True

requirements:
  build:
    - python
    - atom >=0.3.11
    - kiwisolver >0.1.3
    - ply
  run:
    - python
    - python.app       [osx]
    - atom >=0.3.9
    - pyqt
    - kiwisolver >0.1.3
    - ply
    - future

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.signaling
    - enaml.weakmethod
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  license: BSD
  license_file: COPYING.txt
  summary: Declarative DSL for building rich user interfaces in Python
