package:
  name: enaml
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
              )}}
source:
  git_tag: master
  git_url: https://github.com/nucleic/enaml.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - enaml-run = enaml.runner:main
  osx_is_app: True
  skip_compile_pyc:
    - "*/enaml/core/byteplay/*.py"
  ignore_prefix_files:
    - "**/enaml/**/__enamlcache__/*.*.enamlc"

requirements:
  build:
    - python
    - atom >=0.4.2
    - kiwisolver >=1.0.0
    - ply
    - future
  run:
    - python
    - python.app       [osx]
    - atom >=0.4.0
    - pyqt
    - qtpy >=1.3
    - kiwisolver >=1.0.0
    - ply
    - future

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.signaling
    - enaml.weakmethod
    - enaml.core.api
    - enaml.widgets.api
    - enaml.layout.api

about:
  home: https://github.com/nucleic/enaml
  license: BSD
  license_file: COPYING.txt
  summary: Declarative DSL for building rich user interfaces in Python
