package:
  name: argh
  version: "0.26.2"

source:
  fn: argh-0.26.2.tar.gz
  url: https://pypi.python.org/packages/source/a/argh/argh-0.26.2.tar.gz
  md5: edda25f3f0164a963dd89c0e3c619973

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - argh

about:
  home: http://github.com/neithere/argh/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'An unobtrusive argparse wrapper with natural syntax'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
