package:
  name: kiwisolver
  version: 0.1.3.post21+g24d610a

source:
  git_rev: 24d610ad819c2ecfb5395135a54f739bef2e0fb2
  git_url: https://github.com/nucleic/kiwi

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - kiwisolver

about:
  home: https://github.com/nucleic/kiwi
  license: Modified BSD
  summary: 'A fast implementation of the Cassowary constraint solver'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
