package:
  name: pyvisa
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_tag: 1.9.0
  git_url: https://github.com/hgrecco/pyvisa

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - enum34 # [not (py34 or py35 or py36)]

test:
  # Python imports
  imports:
    - pyvisa

about:
  home: http://github.com/hgrecco/pyvisa/
  license: 'MIT License'
  summary: 'Python VISA bindings for GPIB, RS232, and USB instruments'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
